### ISSUE TITLE
Perl length() returns the wrong value on array elements returned by fetchrow_arrayref()

### ISSUE THREAD

**Issue by masterchiefaragorn** [bucardo/dbdpg#72]
Hi,

In the below code:

```
#!/opt/bin/perl

use DBI;

my $db = DBI->connect('dbi:Pg:dbname=main','schemaname','password');
my $st = $db->prepare('SELECT label FROM time_code');
$st->execute;
while (my $rec = $st->fetchrow_arrayref) {
	print 'len: ' . length($rec->[0]) . ' val: ' . $rec->[0] . "\n";
}
$db->disconnect;
```

...the length() call returns the correct value (11) for the first row fetched, and then for all subsequent rows, it returns "11" regardless of the actual length of the string in $rec->[0].  Here's the output:

```
len: 11 val: Office Work
len: 11 val: Warehouse Work
len: 11 val: Holiday
len: 11 val: PTO/Vacation
len: 11 val: Sick Time
```

Is this a DBD::Pg issue or a DBI issue?  I am running DBI 1.643 (latest) and DBD::Pg 3.12 (latest) on Perl 5.26.1 with Postgres 10.13.

Thanks in advance!

**Comment by jonjensen** [comment]
Sadly I can confirm this problem exists on Perl 5.22.0 + DBD::Pg 3.12.0 + Postgres 12. I used nearly your identical script.

The problem did *not* exist on Perl 5.14.1 + DBD::Pg 2.18.1 + Postgres 9.2.

**Comment by jonjensen** [comment]
@masterchiefaragorn Thanks for reporting this! I found using `git bisect` that the bug was introduced between version 2.19.3 and 2.20.1_2 on 2 July 2013.

I added a unit test that demonstrates the problem and found a couple of ways to fix it in https://github.com/bucardo/dbdpg/pull/73 and https://github.com/bucardo/dbdpg/pull/74 and want to hear back from the primary author @turnstep on:

* which fix is better
* whether there could be negative side effects from them
* whether we need similar fixes elsewhere in the code

@machack666 You may be interested to take a look at this too.

**Comment by masterchiefaragorn** [comment]
@jonjensen, Thanks for jumping on this!  It's likely not necessary to say this, but this bug also manifests for the more-oft-used ```fetch()``` method, since that is an alias to ```fetchrow_arrayref()```.

I'm surprised that our team has gone 7 years without encountering this.

**Comment by masterchiefaragorn** [comment]
Thanks, @jonjensen and @turnstep!  I've rolled this out to one production server to see how it behaves in the real world.

**Comment by turnstep** [comment]
This is now part of the 3.13.0 release
